<a href="https://colab.research.google.com/github/Yoon2596/kita_2404/blob/main/m3_%EB%B6%84%EC%84%9D_%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/numpy/numpy_quiz1(%EB%A5%98%EC%9C%A4%EC%84%A0).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy Quiz1

Q1. arange(), reshape() 이용 1차원 2차원 3차원 배열 생성

In [142]:
import numpy as np
arr = np.arange(6).reshape(1, 2, 3)
print(arr, '\n')

arr1 = np.arange(8).reshape(-1)
print(arr1, '\n')
arr2 = np.arange(8).reshape(-1, 2)
arr21 = np.arange(8).reshape(2, -1)
print(arr2, '\n')
print(arr21, '\n')
arr3 = np.arange(10).reshape(2, 5, -1)
print(arr3, '\n')

[[[0 1 2]
  [3 4 5]]] 

[0 1 2 3 4 5 6 7] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]] 

[[0 1 2 3]
 [4 5 6 7]] 

[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]] 



Q2. reshape(-1,-1)을 이용 1차원을 2차원, 3차원으로 2차원을 1차원 3차원으로 3차원을 1차원 2차원으로 변환

In [149]:
# 1차원을 2차원, 3차원
ar1 = np.arange(10).reshape(-1)
ar12 = ar1.reshape(2, -1)
print(ar12, '\n')
ar13 = ar1.reshape(-1, 2, 5)
print(ar13, '\n')

# 2차원을 1차원, 3차원
ar2 = np.arange(10).reshape(5 , 2)
ar21 = ar2.reshape(-1)
print(ar21, '\n')
ar23 = ar2.reshape(2, -1, 5)
print(ar23, '\n')

# 3차원을 1차원, 2차원
ar3 = np.arange(10).reshape(-1, 2, 5)
ar31 = ar3.reshape(-1,)
print(ar31, '\n')
ar32 = ar3.reshape(5, -1)
print(ar32)

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[[0 1 2 3 4]
  [5 6 7 8 9]]] 

[0 1 2 3 4 5 6 7 8 9] 

[[[0 1 2 3 4]]

 [[5 6 7 8 9]]] 

[0 1 2 3 4 5 6 7 8 9] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Q3. Q1 1차원 배열을 실수형으로 변환

In [150]:
arr = np.arange(6)
f_arr = arr.astype('float64')
print(f_arr, f_arr.dtype)

[0. 1. 2. 3. 4. 5.] float64


Q4. Q1 1차원 배열의 dtype을 확인

In [11]:
print(arr.dtype)

int64


Q5. 주어진 배열에서 음수 값을 모두 0으로 변경하세요.

arr = np.array([-5, -3, -1, 0, 1, 3, 5])

In [18]:
arr = np.array([-5, -3, -1, 0, 1, 3, 5])
pos_arr = np.where(arr < 0, 0, arr)
print(pos_arr)

[0 0 0 0 1 3 5]


Q6. 1 ~ 100 까지 배열에서 3의 배수인 것만을 출력

In [152]:
a6 = np.arange(1, 101)
# print(a6)
mask = a6 % 3 == 0
# print(mask, '\n')
print(a6[mask])

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


Q7. 1 ~ 100 까지 배열에서 5의 배수이면서 2의 배수인 것만을 출력

In [154]:
a7 = np.arange(1, 101)
q7 = []
for i in a7:
    if (i % 5 == 0) & (i % 2 == 0):
        q7.append(i)
print(q7)

arr7 = a7[(a7 % 5 == 0) & (a7 % 2 == 0)]
arr7

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

Q8. 1 ~ 100 까지 배열에서 3의 배수이거나 5의 배수인 것만을 출력

In [24]:
a8 = np.arange(1, 101)
q8 = []
for i in a8:
    if (i % 5 == 0) | (i % 3 == 0):
        q8.append(i)
print(q8)

[3, 5, 6, 9, 10, 12, 15, 18, 20, 21, 24, 25, 27, 30, 33, 35, 36, 39, 40, 42, 45, 48, 50, 51, 54, 55, 57, 60, 63, 65, 66, 69, 70, 72, 75, 78, 80, 81, 84, 85, 87, 90, 93, 95, 96, 99, 100]


Q9. 101 ~ 150 사이의 정수를 랜덤하게 추출, 2행 5열 다차원 배열을 생성 후 전치하세요

In [157]:
a = np.random.choice(np.arange(101, 151), 10)
b = np.random.randint(101, 151, size=(2, 5))

print(a, '\n')
print(b, '\n')
# ar9 = np.random.randint(101, 151)
# print(ar9)
q9 = np.array([a]).reshape(2, 5)
print(q9, '\n')
t_q9 = q9.T
print(t_q9)
# print(sort(q9))
# print(sorted(q9))

[101 144 127 103 144 107 122 103 129 143] 

[[127 108 130 147 111]
 [119 105 130 140 108]] 

[[101 144 127 103 144]
 [107 122 103 129 143]] 

[[101 107]
 [144 122]
 [127 103]
 [103 129]
 [144 143]]


Q10. 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하세요.

In [62]:
a10 = np.random.randn(5, 5)
print(a10)

[[ 1.13941604 -0.75416381  0.75407155 -0.97238922 -0.78828881]
 [ 0.84499472  2.06618287 -0.75854749  0.75308928  0.5837779 ]
 [ 0.27296061 -0.26671621 -0.75707694  1.7126685   1.23495247]
 [-0.37766362 -0.52637618 -0.17572355 -0.81059924  1.08270105]
 [-0.35205272  0.87513271 -0.57209832 -0.19720417 -0.29701824]]


Q11. original_array를 1차원 배열로 변환하여 출력하세요.

In [160]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
print(original_array, '\n')
array_1d = original_array.reshape(-1)
flatten = original_array.flatten()
print(array_1d, '\n')
print(flatten)

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6] 

[1 2 3 4 5 6]


Q12. 주어진 2차원 배열에서 첫 번째 행을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [170]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])
print(original_array, '\n')
v_array = original_array[0, :]
print(v_array, '\n')
v_array[1] = 100
print(v_array, '\n')
print(original_array, '\n')

[[1 2 3]
 [4 5 6]] 

[1 2 3] 

[  1 100   3] 

[[  1 100   3]
 [  4   5   6]] 



Q13. 주어진 3차원 배열에서 첫 번째 2차원 배열을 view로 생성하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [176]:
original_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(original_array, '\n')

slice_view = original_array[0, :, :]
print(slice_view, '\n')

slice_view[1][1] = 20
slice_view[0, 0] = 10
print(slice_view, '\n')

print(original_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

[[1 2 3]
 [4 5 6]] 

[[10  2  3]
 [ 4 20  6]] 

[[[10  2  3]
  [ 4 20  6]]

 [[ 7  8  9]
  [10 11 12]]]


Q14. 주어진 2차원 배열을 1차원 배열 view로 reshape하고, 이 view를 수정하여 원본 배열에 반영되도록 하세요.

original_array = np.array([[1, 2, 3], [4, 5, 6]])

In [179]:
original_array = np.array([[1, 2, 3], [4, 5, 6]])

print(original_array, '\n')
new_array = original_array.reshape(-1)
print(new_array, '\n')
new_array[0] = 99
print(new_array, '\n')
print(original_array)

[[1 2 3]
 [4 5 6]] 

[1 2 3 4 5 6] 

[99  2  3  4  5  6] 

[[99  2  3]
 [ 4  5  6]]


Q15. np.ones((10,10))을 아래와 같이 출력하세요.
```
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
 ```

In [80]:
a15 = np.ones((10, 10))
print(a15)
a15[1:9, 1:9] = 0
print()
print(a15)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


Q16. Q. 1 ~ 100을 아래와 같이 출력하세요.

```
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]]
 ```

In [200]:
a16 = np.arange(1, 101).reshape(10, 10)
ar16 = np.arange(1, 101).reshape(10, 10)
print(a16)
print()

for i in range(10):
    if i % 2 == 1:
        reverse = a16[i][::-1]
        # print(a)
        a16[i] = reverse
    else:
        a16[i]

ar = []
for i in range(10):
    if i % 2 == 1:
        ar16[i] = ar16[i][::-1]
        ar.append(a16[i])
    else:
        ar.append(a16[i])

print(a16, '\n')
print(np.array(ar))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] 

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40 

Q17. np.ones((5,5))을 아래와 같이 출력하세요.
```
[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]]
```

In [105]:
a17 = np.ones((5, 5))
print(a17)
print()
# b17 = np.zeros((10, 10))
# c = a17.union(b17)
# print(c)





q17 = np.zeros((10, 10))
# print(q17)
q17[2:8, 2:8] = 1
print()
print(q17)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [202]:
a17 = np.ones((5, 5))
np.pad(a17, pad_width=2, mode='constant', constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Q18. np.arange(4)을 이용해서 아래와 같이 출력하세요.
```
[[0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0],
 [0, 2, 0, 0, 0],
 [0, 0, 3, 0, 0],
 [0, 0, 0, 4, 0]]
```

In [99]:
a18 = np.arange(4)+1
print(a18)
q18 = np.zeros((5, 5))
# print(q18)
print()
q18[1][0] = a18[0]
q18[2][1] = a18[1]
q18[3][2] = a18[2]
q18[4][3] = a18[3]
print(q18)



[1 2 3 4]

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [212]:
np.diag(np.arange(4)+1, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

Q19. Q. np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)
```
[[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0],
[0, 1, 0, 1, 0, 1, 0, 1],
[1, 0, 1, 0, 1, 0, 1, 0]]
```

In [214]:
a19 = np.zeros((8, 8))

a19[1::2, ::2] = 1
a19[::2, 1::2] = 1
print(a19)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Q20. np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요.

In [216]:
a20 = np.arange(336).reshape(6, 7, 8)
print(a20, '\n')

index_100 = np.unravel_index(99, a20.shape)
index_100

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

(1, 5, 3)