<a href="https://colab.research.google.com/github/Yoon2596/kita_2404/blob/main/m3_%EB%B6%84%EC%84%9D_%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/%EA%B3%BC%EC%A0%9C/%EA%B3%BC%EC%A0%9C_0611.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task1_0611. 주어진 대각 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

D = np.diag([1, 2, 3])

In [2]:
import numpy as np
D = np.diag([1, 2, 3])
print(D, '\n')
inverse_D = np.linalg.inv(D)
print(inverse_D, '\n')

check_D = np.dot(D, inverse_D)
print(check_D)  # 단일행렬로 역행렬 확인

[[1 0 0]
 [0 2 0]
 [0 0 3]] 

[[1.         0.         0.        ]
 [0.         0.5        0.        ]
 [0.         0.         0.33333333]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Task2_0611. 임의의 상삼각 행렬을 생성하고, 그 행렬로 부터 하삼각 행렬을 구하여 출력하세요.

In [7]:
t2 = np.random.randint(1, 9, size=(4,4))
print(t2, '\n')

upper_t2 = np.triu(t2)
lower_ct2 = np.tril(t2)
print(upper_t2, '\n')

lower_t2  = upper_t2.T
print(lower_t2, '\n')
print(lower_ct2)

[[2 1 5 5]
 [1 2 2 6]
 [3 7 8 8]
 [2 2 7 4]] 

[[2 1 5 5]
 [0 2 2 6]
 [0 0 8 8]
 [0 0 0 4]] 

[[2 0 0 0]
 [1 2 0 0]
 [5 2 8 0]
 [5 6 8 4]] 

[[2 0 0 0]
 [1 2 0 0]
 [3 7 8 0]
 [2 2 7 4]]


Task3_0611. 주어진 행렬의 역행렬을 구하고, 역행렬이 맞는지 확인하세요.

A = np.array([[4, 7], [2, 6]])

In [10]:
A = np.array([[4, 7], [2, 6]])
print(A, '\n')

inverse_A = np.linalg.inv(A)
print(inverse_A, '\n')

check_A = A @ inverse_A
print(check_A, '\n')

# 단위 행렬
I = np.eye(2)

# 단위행렬로 같은지 확인
print(np.allclose(check_A, I))

[[4 7]
 [2 6]] 

[[ 0.6 -0.7]
 [-0.2  0.4]] 

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]] 

True


Task4_0611. 주어진 데이터 포인트와 모델 파라미터를 사용하여 선형 회귀 모델의 예측값을 계산하세요.

X = np.array([1, 2, 3])

- 1단계 : 주어진 입력 데이터 포인트 X와 모델 파라미터 θ를 정의.
- 2단계 : 행렬 곱을 사용하여 예측값 y를 계산.

In [ ]:
X = np.array([1, 2, 3])
print(X, '\n')
theta = 32
# np.dot(X, Y) = theta
# Y1 + 2Y2 + 3Y3 = 32
# 임의의 해 4, 5, 6 = 4 + 10 + 18 = 32
# 임의의 해 7, 8, 3 = 7 + 16 + 9 = 32
# 해당 해 확인
Y1 = np.array([4, 5, 6])
Y2 = np.array([7, 8, 3])

check_t1= np.dot(X, Y1)
check_t2= np.dot(X, Y2)
print(check_t1) #값이 같으므로 Y 벡터 확인
print(check_t2) #값이 같으므로 Y 벡터 확인

[1 2 3] 

32
32


In [11]:
# 강사님 버전 문제4

# 입력 데이터 포인트 (1, x1, x2)
X = np.array([1, 2, 3])

# 모델 파라미터 (bias, w1, w2)
theta = np.array([0.5, 1.5, -2])

# 선형 회귀 모델의 예측값 계산
y_pred = np.dot(X, theta)

print('Input Data Point X : ', X)
print('Model Parameters theta :', theta)
print('Predicted Value y :', y_pred)

Input Data Point X :  [1 2 3]
Model Parameters theta : [ 0.5  1.5 -2. ]
Predicted Value y : -2.5


Task5_0611. 주어진 입력 벡터와 가중치 행렬을 사용하여 신경망의 단일 계층 출력을 계산하세요.

X = np.array([0.5, 1.0, -1.5])

- 1단계: 입력 벡터 X와 가중치 행렬 W를 정의.
- 2단계: 행렬 곱을 사용하여 계층의 출력을 계산.

In [15]:
X = np.array([0.5, 1.0, -1.5])
# W1 = np.array([0.01, 0.5, 0.7])
# W2 = np.array([0.1, 0.5, 0.7])
# W3 = np.array([0.6, 0.2, 0.01])

# V = X @ W
# V1 = np.matmul(X, W1)
# V2 = np.matmul(X, W2)
# V3 = np.matmul(X, W3)
# print(V1)
# print(V2)
# print(V3)

# 가중치 행렬 W 정의
W = np.array([
    [0.01, 0.5, 0.7],
    [0.1, 0.5, 0.7],
    [0.6, 0.2, 0.01]
])
# 계층의 출력 계산
V = np.matmul(W, X)
print(V)

[-0.545 -0.5    0.485]


In [14]:
# 강사님 버전 문제5
# W는 가중치 행렬, X는 입력 벡터이고 일반적인 표기방법은 WX
# 입력 백터 (x1, x2, x3)
X = np.array([0.5, 1.0, -1.5])

# 가중치 행렬 (각 행이 뉴런의 가중치를 나타냄)
W = np.array([
    [0.2, -0.3, 0.5],
    [0.4, 0.1, -0.2],
    [-0.5, 0.4, 0.3]
])

# 신경망의 단일 계층 출력 계산
output = np.dot(W, X)

print('Input Vector X : ', X)
print('Weight Matrix W :\n', W)
print('Layer Output :\n', output)

Input Vector X :  [ 0.5  1.  -1.5]
Weight Matrix W :
 [[ 0.2 -0.3  0.5]
 [ 0.4  0.1 -0.2]
 [-0.5  0.4  0.3]]
Layer Output :
 [ 1.25 -0.65 -0.4 ]


Task6_0611. 주어진 입력 벡터에 대해 신경망의 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산하세요.

X = np.array([1, -2, 3])

- 1단계: 입력 벡터 X를 정의.
- 2단계: 가중치 행렬 W와 편향 벡터 b를 정의.
- 3단계: 활성화 함수(ReLU, 시그모이드)를 적용하여 출력을 계산
활성화 함수 적용<br>
output_relu = relu(Z)<br>
output_sigmoid = sigmoid(Z)

In [ ]:
X = np.array([1, -2, 3])
# print(X, '\n')

def relu(x):
    return np.maximum(0, x)


def sigmoid(x):
    return 1/(1+np.exp(-x))

# 가중치 행렬 W 정의
W = np.array([
    [0.01, 0.5, 0.7],
    [0.1, 0.5, 0.7],
    [0.6, 0.2, 0.01]
])

b = .7

Z = np.dot(X, W) + b



output_relu = relu(Z)
print(output_relu)
output_sigmoid = sigmoid(Z)
print(output_sigmoid)

[2.31 0.8  0.03]
[0.90970186 0.68997448 0.50749944]


In [17]:
# 강사님 문제6

# 활성화 함수 정의
def relu(x):
    return np.maximum(0, x)


def sigmoid(x):
    return 1/(1+np.exp(-x))

# 입력 벡터 정의
X = np.array([1, -2, 3])

# 가중치 행렬과 편향 벡터 정의
#(Weight Matrix W / Bias Vector b)
W = np.array([
    [0.2, -0.5, 0.3],
    [0.4, 0.1, -0.2],
    [-0.3, 0.4, 0.6]
])

b = np.array([0.1, -0.2, 0.3])

# 신경망의 선형 변환 계산
Z = np.dot(W, X) + b

# 활성화 함수 적용
output_relu = relu(Z)
output_sigmoid = sigmoid(Z)


print('Linear Transformation Z :', Z, '\n')
print(output_relu, '\n')
print(output_sigmoid)

Linear Transformation Z : [ 2.2 -0.6  1. ] 

[2.2 0.  1. ] 

[0.90024951 0.35434369 0.73105858]


Task7_0611. 주어진 선형 방정식을 행렬 형태로 나타내고, 역행렬을 사용하여
x와 y를 구하세요.

$\begin{cases}
3x + 4y = 10 \\
2x + y = 5
\end{cases}$

단계:
1. 계수 행렬 A와 결과 벡터 b를 정의.
2. 행렬 A의 역행렬을 구한다.
3. 역행렬을 사용하여 변수 x를 구한다.

In [ ]:
from sympy import symbols, solve

x, y = symbols('x, y')
print(solve([
    3*x + 4*y - 10,
    2*x + y - 5
]), '\n')

# [[3, 4], [2, 1]] dot [x, y] = [10, 5]
# [x, y] = [10, 5] dot inv.[[3, 4], [2, 1]]
A = np.array([[3, 4], [2, 1]])
print(A, '\n')
inv_A = np.linalg.inv(A)
B = np.array([10, 5])
print(inv_A, '\n')
result = np.dot(inv_A, B)
print(result)

{x: 2, y: 1} 

[[3 4]
 [2 1]] 

[[-0.2  0.8]
 [ 0.4 -0.6]] 

[2. 1.]


[풀이]
주어진 선형방정식을 행렬 형태로 나타내면 다음과 같다: \\
$A\mathbf{x} = \mathbf{b}$ \\
여기서 \\
$A = \begin{bmatrix}3 & 4 \\2 & 1\end{bmatrix}$,

$\mathbf{x} = \begin{bmatrix}x \\y\end{bmatrix}$,

$\mathbf{b} = \begin{bmatrix}10 \\5\end{bmatrix}$

$\mathbf{x} = A^{-1} \mathbf{b}$

In [21]:
# 강사님 버전 문제7

# 계수 행렬 A와 결과 벡터 B
A = np.array([[3, 4], [2, 1]])
B = np.array([10, 5])

# 역 행렬 계산
inv_A = np.linalg.inv(A)

# 해 계산
x = np.dot(inv_A, B)

print('Coefficient Matrix A :\n', A, '\n')
print('Result Vector B : ', B, '\n')
print('Inverse of A (inv_A) :\n', inv_A, '\n')
print('Solution Vector x : ', x, '\n')

Coefficient Matrix A :
 [[3 4]
 [2 1]] 

Result Vector B :  [10  5] 

Inverse of A (inv_A) :
 [[-0.2  0.8]
 [ 0.4 -0.6]] 

Solution Vector x :  [2. 1.] 



Task8_0611. 주어진 2D 평면의 점을 특정 변환 행렬을 사용하여 변환한 후, 변환된 좌표를 원래 좌표로 되돌리세요.

원래 점의 좌표 p와 변환 행렬 T 정의<br>
p = np.array([1, 2])<br>
T = np.array([[2, 0], [0, 3]])

단계
1. 원래 점의 좌표 p와 변환 행렬 T를 정의.
2. 변환 행렬 T를 사용하여 새로운 좌표 p'를 계산.
3. 변환 행렬 T의 역행렬을 사용하여 새로운 좌표 p에서 원래 좌표 p를 복원.

In [ ]:
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])

# 새로운 좌표 계산
new_v = np.dot(p, T)
print(new_v, '\n')

# T의 역행렬 사용
inv_T = np.linalg.inv(T)
origin_p = np.dot(inv_T, new_v)
# origin_p = np.dot(new_v, inv_T)
print(origin_p)

[2 6] 

[1. 2.]


In [23]:
# 강사님 버전 문제8

# 원래 점의 좌표 p의 변환 행렬 T 정의
p = np.array([1, 2])
T = np.array([[2, 0], [0, 3]])

# 새로운 좌표 p' 계산
p_prime = np.dot(T, p)

# 변환 행렬 T의 역행렬 계산
inv_T = np.linalg.inv(T)

# 원래 좌표 p 복원
p_restored = np.dot(inv_T, p_prime)

print('Original Point p :', p, '\n')
print('Transformation Matrix T :\n', T, '\n')
print('Transformed Point p prime : ', p_prime, '\n')
print('Inverse of T (inv_T) :\n', inv_T, '\n')
print('Restored Point p : ', p_restored, '\n')

Original Point p : [1 2] 

Transformation Matrix T :
 [[2 0]
 [0 3]] 

Transformed Point p prime :  [2 6] 

Inverse of T (inv_T) :
 [[0.5        0.        ]
 [0.         0.33333333]] 

Restored Point p :  [1. 2.] 



In [ ]:
from sympy import symbols, solve

x, y = symbols('x, y')
print(solve([
    2*x + 3*y - 5,
    4*x + y - 6
]), '\n')

{x: 13/10, y: 4/5} 

