<a href="https://colab.research.google.com/github/Yoon2596/kita_2404/blob/main/m3_%EB%B6%84%EC%84%9D_%EB%9D%BC%EC%9D%B4%EB%B8%8C%EB%9F%AC%EB%A6%AC/pandas_1_%EB%8D%B0%EC%9D%B4%ED%84%B0%EA%B5%AC%EC%A1%B0(0527).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####Contents
 - 데이터 구조 Series, DataFrame
 - 인덱스, 생성, 선택, 추가, 변경, 삭제, 전치
 - 파이썬 자료형과 양방향 변환

#### 판다스
Pandas는 파이썬에서 데이터 분석 및 조작을 위한 강력하고 유연한 오픈 소스 라이브러리. Series와 DataFrame 같은 고수준의 데이터 구조를 제공하여, 복잡한 데이터 조작을 직관적이고 효율적으로 수행할 수 있게 한다.

[Pandas의 주요 역할과 기능]

* DataFrame과 Series: 2차원 테이블과 1차원 배열 형태의 데이터 구조를 제공
* 데이터 처리: 결측값 처리, 데이터 정제, 필터링, 병합, 연결 및 변환 등을 위한 다양한 기능을 제공
* 데이터 분석: 기술통계, 그룹화, 시계열 분석 등 복잡한 분석 작업을 제공
* 입출력 기능: CSV, Excel, SQL, JSON 등 다양한 파일 형식의 데이터를 읽고 쓸 수 있는 기능을 제공
* 시각화 지원: 매트플롯립과 연동하여 데이터 시각화가 가능하도록 제공
* 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성. 시리즈와 데이터프레임은 대표적인 클래스 객체임
* 시리즈 인덱스는 데이터 값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)

In [ ]:
# 시리즈 클래스 만들기
# pandas 불러오기(pd)
import pandas as pd

# k:v 구조를 갖는 딕셔너리를 만들고 변수 dict_data에 저장
dict_data = {'a':1, 'b':2, 'c':3}

sr = pd.Series(dict_data)
print(sr, type(sr))

a    1
b    2
c    3
dtype: int64 <class 'pandas.core.series.Series'>


In [ ]:
# 리스트를 시리즈로 변환
list_data = ['2019-01-02', 3.14, 'ABC', 100, True]

sr = pd.Series(list_data)
print(sr, type(sr))

0    2019-01-02
1          3.14
2           ABC
3           100
4          True
dtype: object <class 'pandas.core.series.Series'>


In [ ]:
# 인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
print(list(idx))
print(val)

RangeIndex(start=0, stop=5, step=1)
[0, 1, 2, 3, 4]
['2019-01-02' 3.14 'ABC' 100 True]


In [ ]:
# 튜플을 시리즈로 변환
tup_data = ('kevin', '2019-07-02', '남', True)

td = pd.Series(tup_data)
td = pd.Series(tup_data, index = ['이름', '생년월일', '성별', '학생여부'])

print(td, type(td))
tidx = td.index
tval = td.values
print(tidx)
print(list(tidx))
print(tval)
print(list(tval))

이름           kevin
생년월일    2019-07-02
성별               남
학생여부          True
dtype: object <class 'pandas.core.series.Series'>
Index(['이름', '생년월일', '성별', '학생여부'], dtype='object')
['이름', '생년월일', '성별', '학생여부']
['kevin' '2019-07-02' '남' True]
['kevin', '2019-07-02', '남', True]


In [ ]:
sr = [1, 2, 3, 4, 5]
sr[1:3]  # 슬라이싱

[2, 3]

In [ ]:
# 인덱싱
print(td[0])
print(td['이름'])
print(td[[1, 2]])   # 시리즈에서 위치 기반 인덱싱을 사용해서 여러 요소를 선택 가능
# print(td[1, 2])   # 파이썬의 기본 인덱싱 방식으로  sr[1]와 같은 형태를 사용 or 슬라이싱

kevin
kevin
생년월일    2019-07-02
성별               남
dtype: object


In [ ]:
# 배열
import numpy as np

s1 = np.arange(11, 21, 2)
print(s1, type(s1))
print()
s2 = pd.Series(s1, index=list('abcde'))
print(s2, type(s2))

[11 13 15 17 19] <class 'numpy.ndarray'>

a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


In [ ]:
#Q. 배열을 생성 후 시리즈로 변환하여 아래와 같이 출력하세요

data = np.arange(1000, 5000, 1000)
state = ['California','Ohio','Oregon','Texas']

import pandas as pd
q1 = pd.Series(data, index=state)
q1.name = 'population'
q1.index.name = 'state'
print(q1)

state
California    1000
Ohio          2000
Oregon        3000
Texas         4000
Name: population, dtype: int64


None과 np.nan의 차이점
- None은 파이썬의 내장형 객체로 주로 객체형 데이터에서 사용
- np.nan은 부동 소수점으로 취급되며 주로 숫자형 데이터에서 사용

연산 시 np.non은 NaN  결과를 반환하는 반면  None은 TypeError를 발생시킨다

In [ ]:
# 결측치 : 수집된 데이터 셋 중 관측되지 않은 특정 확률변수의 값을 의미한다.
# 값의 특성은 0, NaN(Not Available) 이며 발생 시 잘못된 분석 결과를 낳거나 분석 시 코드 대입 경우 에러가 발생할 수 있다
q1.California = np.nan
q1


state
California       NaN
Ohio          2000.0
Oregon        3000.0
Texas         4000.0
Name: population, dtype: float64

In [ ]:
null_mask = q1.isnull()
print(null_mask)

state
California     True
Ohio          False
Oregon        False
Texas         False
Name: population, dtype: bool


In [ ]:
not_null_mask = q1.notnull()
not_null_mask

state
California    False
Ohio           True
Oregon         True
Texas          True
Name: population, dtype: bool

In [ ]:
filled_series = q1.fillna(0)
filled_series

state
California       0.0
Ohio          2000.0
Oregon        3000.0
Texas         4000.0
Name: population, dtype: float64

In [ ]:
q1.California = np.nan
q1

state
California       NaN
Ohio          2000.0
Oregon        3000.0
Texas         4000.0
Name: population, dtype: float64

In [ ]:
# 결측치 찾는 법 (1개 있음을 확인)
q1.isnull().sum()
# or
q1.isna().sum()

1

In [ ]:
# 삭제하는 법
dropped_series = q1.dropna()
dropped_series

state
Ohio      2000.0
Oregon    3000.0
Texas     4000.0
Name: population, dtype: float64

In [ ]:
# 제거 되었는지 확인
dropped_series.isnull().sum()

0

In [ ]:
print(s2)
print(type(s2))

a    11
b    13
c    15
d    17
e    19
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
# Series -> List
list_from_series = s2.tolist()
list_from_series

[11, 13, 15, 17, 19]

In [ ]:
# Series -> dict
dict_from_series = s2.to_dict()
dict_from_series

{'a': 11, 'b': 13, 'c': 15, 'd': 17, 'e': 19}

In [ ]:
# Series -> DataFrame
df_from_series = s2.to_frame(name='Value')
df_from_series
print(df_from_series, type(df_from_series))

   Value
a     11
b     13
c     15
d     17
e     19 <class 'pandas.core.frame.DataFrame'>


Q. 아래 시리즈에서 null값을 2개 입력 후 그 값을 0으로 대체 후 null값 여부를 확인한 후 출력하세요.

In [ ]:
import pandas as pd
import numpy as np

# 1. Series 생성
s = pd.Series([5, 15, 25, 35, 45], index=['x', 'y', 'z', 'w', 'v'])

s.x = np.nan
s.w = np.nan
print(s)
print('null값의 개수 :', s.isnull().sum())

print()

s['x'] = np.nan
s['z'] = np.nan
print(s)
print('null값의 개수 :', s.isna().sum())


print()
s_filled = s.fillna(0)
print(s_filled)

x     NaN
y    15.0
z    25.0
w     NaN
v    45.0
dtype: float64
null값의 개수 : 2

x     NaN
y    15.0
z     NaN
w     NaN
v    45.0
dtype: float64
null값의 개수 : 3

x     0.0
y    15.0
z     0.0
w     0.0
v    45.0
dtype: float64


Q. 주어진 리스트 [1, 2, 3, 4, 5]를 Pandas Series로 변환하고, 각 원소에 10을 더한 Series를 출력하세요.

In [ ]:
import pandas as pd

# 주어진 리스트
data_list = [1, 2, 3, 4, 5]

# 데이터 시리즈로 변환
dl1 = pd.Series(data_list)

# +-각 원소에 10 더함
dl1 = dl1 + 10

print(dl1)

0    11
1    12
2    13
3    14
4    15
dtype: int64


Q. Series [10, 20, 30, 40, 50]를 생성하고 인덱스를 ['a', 'b', 'c', 'd', 'e']로 설정하세요. 인덱스를 기준으로 Series를 정렬한 결과를 출력하세요.

In [ ]:
import pandas as pd

# 주어진 데이터와 인덱스
data = [10, 20, 30, 40, 50]
index = ['b', 'd', 'e', 'a', 'c']

dl2 = pd.Series(data, index=index)
print(dl2)

# sort_index() : 인덱스를 기준으로 정렬
sorted_dl2 = dl2.sort_index()

print(sorted_dl2)

b    10
d    20
e    30
a    40
c    50
dtype: int64
a    40
b    10
c    50
d    20
e    30
dtype: int64


Q. Series ['a':1, 'b':2, 'c':3, 'd':4, 'e':5]에서 인덱스 'b', 'd'에 해당하는 원소를 선택하여 출력하세요.

In [ ]:
dict1 = { 'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
dl3 = pd.Series(dict1)
print(dl3[['b', 'd']])

print()

dl3_1 = pd.Series({'a':1, 'b':2, 'c':3, 'd':4, 'e':5})
print(dl3_1[['b', 'd']])

b    2
d    4
dtype: int64

b    2
d    4
dtype: int64


#### 데이터프레임
* 데이터프레임은 2차원 배열. R의 데이터프레임에서 유래.
* 데이터프레임의 열은 각각 시리즈 개체.
* 시리즈를 열벡터라고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를
  기준으로 줄지어 결합된 2차원 벡터 또는 행렬.
* 선형대수학에서 열 벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
* 행 벡터(1 x m 행렬)은 m원소들의 단일 행 행렬.
* 리스트, 딕셔너리, ndarray 등 다양한 데이터로부터 생성
* 반대로 리스트, 딕셔너리, ndarray 등으로 변환될 수 있음

In [ ]:
import numpy as np

# 랜덤 숫자를 해당 번호에 고정시켜줌
np.random.seed(0)
np.random.randint(100, 120, size=(3,3))

array([[112, 115, 100],
       [103, 103, 107],
       [109, 119, 118]])

In [ ]:
# 배열을 데이터프레임으로 변환
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

print()

df = pd.DataFrame(data, index=['d1', 'd2', 'd3'], columns = ['pd', 'sales', 'inv'])
print(df, type(df))

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>

     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118 <class 'pandas.core.frame.DataFrame'>


In [ ]:
# 데이터프레임에서 1개의 열만 뽑을 경우
print(df.pd, type(df.pd))

d1    112
d2    103
d3    109
Name: pd, dtype: int64 <class 'pandas.core.series.Series'>


In [ ]:
# 인덱스 설정없이 데이터프레임을 만들면 자동으로 숫자로 정해줌
df = pd.DataFrame(data, columns = ['pd', 'sales', 'inv'])
print(df, type(df))

    pd  sales  inv
0  112    115  100
1  103    103  107
2  109    119  118 <class 'pandas.core.frame.DataFrame'>


#### Pandas의 iloc와 loc 메서드
DataFrame과 Series에서 데이터의 특정 위치나 라벨에 접근하기 위한 중요한 도구이며 두 메서드는 각각 고유한 용도를 가지고 있다.

- iloc (Integer Location)
  - 정수 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 특정 위치에 있는 데이터를 선택할 때 사용.
  - 슬라이싱 지원: Python 리스트와 유사하게 슬라이싱을 지원.
  - 끝점 포함하지 않음: 슬라이싱 시 끝점은 포함하지 않는다.
- loc (Label Location)
  - 라벨 인덱스 기반으로 데이터에 접근하는 메서드. 즉, DataFrame이나 Series의 라벨 이름을 사용하여 데이터에 접근.
  - 슬라이싱 지원: 라벨을 사용하여 슬라이싱을 지원.
  - 끝점 포함: 슬라이싱 시 끝점을 포함.

####iloc

In [ ]:
import pandas as pd

# 데이터프레임 생성
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}

df = pd.DataFrame(data)
print(df, '\n')

# 첫 번째 행, 두 번째 열의 값 선택
print(df.iloc[0, 1])
# 창 번쨰 부터 두 번째 행, 첫 번째부터 두 번째 열 선택
print(df.iloc[0:2, 0:2])

   A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12 

5
   A  B
0  1  5
1  2  6


####loc

In [ ]:
data = {
    'A': [1, 2, 3, 4],
    'B': [5, 6, 7, 8],
    'C': [9, 10, 11, 12]
}

df = pd.DataFrame(data, index = ['a', 'b', 'c' ,'d'])
print(df, '\n')

# 인덱스 'a' /  열 'B'의 값 선택
print(df.loc['a', 'B'], '\n')

# 인덱스 'a' 부터 'b' / 열 'A' 부터 'B'의 선택
print(df.loc['a':'b', 'A':'B'])

   A  B   C
a  1  5   9
b  2  6  10
c  3  7  11
d  4  8  12 

5 

   A  B
a  1  5
b  2  6


In [ ]:
np.random.seed(0)
data = np.random.randint(100, 120, size=(3,3))
print(data, type(data))

print()

df = pd.DataFrame(data, index=['d1', 'd2', 'd3'], columns = ['pd', 'sales', 'inv'])
print(df, type(df))

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>

     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118 <class 'pandas.core.frame.DataFrame'>


In [ ]:
# pandas indexing : iloc 정수 인덱스, loc 이름 인덱스

print(df.iloc[1], '\n')
print(df.loc['d2'])

pd       103
sales    103
inv      107
Name: d2, dtype: int64 

pd       103
sales    103
inv      107
Name: d2, dtype: int64


In [ ]:
# 같은 행을 다른 표현으로 표시
print(df.iloc[1:2], '\n')
print(df.iloc[1, :], '\n')
print(df.loc['d2'])

     pd  sales  inv
d2  103    103  107 

pd       103
sales    103
inv      107
Name: d2, dtype: int64 

pd       103
sales    103
inv      107
Name: d2, dtype: int64


In [ ]:
# 표에서 107만 선택하기
print(df.iloc[1, 2], '\n')
print(df.loc['d2', 'inv'], '\n')

107 

107 



In [ ]:
# 한 행에 모두 0 대입
df.iloc[2, :] = 0
print(df, '\n')

df.loc['d3', :] = 0
print(df)

     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0 

     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0


In [ ]:
# 추가 행에 0 대입
# 추가 행은 무조건 loc만 써야함
df.loc['d4'] = 0
print(df)

     pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0


In [ ]:
# 추가 열에 10 대입
df.loc[:, 'stuck'] = 10
print(df)

     pd  sales  inv  stuck
d1  112    115  100     10
d2  103    103  107     10
d3    0      0    0     10
d4    0      0    0     10


####[파이썬 random 함수]

In [ ]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0 사이
print(random.randint(1,10),'\n') # 1에서 10사이의 정수중에서 난수 값 리턴
print(random.uniform(10,20), '\n') # min max 사이 float 리턴
print(random.randrange(10), '\n') # 지정 범위 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li = [1,2,3,4,5]
print(random.sample(li,3),'\n') # 리스트 요소를 중복이 안되게 리턴
random.shuffle(li) # 리스트 요소를 다시 섞어서 리턴
print(li)

0.3675501994052407 

1 

14.008094212942485 

0 

5 

[4, 2, 1] 

[1, 4, 5, 2, 3]


####[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터의 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [ ]:
import numpy as np
print(np.random.randint(6), '\n') # 0 ~ 5까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1 ~ 19까지 정수인 난수 1개
print(np.random.randint(10, size=10), '\n') # 0 ~ 9까지 정수인 난수 10개
print(np.random.randint(10,20, size=10),'\n') # 10 ~ 19까지 정수인 난수 10개
print(np.random.randint(10,20, size=(3,5))) # 10 ~ 19까지 정수인 난수로 3행 5열 배열 생성

4 

7 

[8 8 1 6 7 7 8 1 5 9] 

[18 19 14 13 10 13 15 10 12 13] 

[[18 11 13 13 13]
 [17 10 11 19 19]
 [10 14 17 13 12]]


In [ ]:
# id, gender, age, region
import numpy as np
import pandas as pd

#id 설정
id = np.arange(1, 1001)
i1 = pd.Series(id)

# gender 설정
gender = np.random.randint(2, size=1000)
g1 = pd.Series(gender)

# age 설정
age = np.random.randint(1, 101, size=1000)
a1 = pd.Series(age)

# region 설정
region = np.random.randint(1, 11, size=1000)
r1 = pd.Series(region)

df = pd.concat([i1, g1, a1, r1], axis=1)

# inplace = True : 바뀐 컬럼을 계속 반영하겠다 / 안하면 일시적으로만 반환됨
df.rename(columns = {0: 'id', 1: 'gender', 2: 'age', 3: 'region'}, inplace=True)
df.head()

id  gender  age  region
0   1       0   82       5
1   2       1   72       6
2   3       1   22       9
3   4       1   24       2
4   5       1  100       3

In [ ]:
#id 설정
id = np.arange(1, 1001)
i1 = pd.Series(id)

# gender 설정
gender = np.random.randint(2, size=1000)
g1 = pd.Series(gender)

# age 설정
age = np.random.randint(1, 101, size=1000)
a1 = pd.Series(age)

# region 설정
region = np.random.randint(1, 11, size=1000)
r1 = pd.Series(region)

df1 = pd.DataFrame(data = {'id':i1, 'gender':g1, 'age':a1, 'region':r1})
df1.head()

id  gender  age  region
0   1       1   57       2
1   2       0   98       2
2   3       0   33       3
3   4       0   38       3
4   5       0   61       5

In [ ]:
# 삭제 방법 (0번 인덱스 행 삭제)
df.drop([0], axis=0, inplace=True)
df.head()

id  gender  age  region
1   2       1   72       6
2   3       1   22       9
3   4       1   24       2
4   5       1  100       3
5   6       1   11       1

####at
- 라벨 기반 인덱싱을 사용
- 주로 단일 값에 접근 할 때 loc 접금자 보다 빠르다
- 여러 값을 동시에 접근하려면 loc 접근자를 사용

In [ ]:
# at : [행, 열]
print(df.at[3, 'age'])

# 단일 값 업데이트 가능# at : [행, 열]
print(df.at[3, 'age'])

# 단일 값 업데이트 가능
df.at[3, 'age'] = 25

print(df.loc[3, 'age'])

df.head(7)

20
25


id  gender  age  region
1   2       1   72       6
2   3       1   22       9
3   4       1   25       2
4   5       1  100       3
5   6       1   11       1
6   7       0   47      10
7   8       0   18       2

In [ ]:
# df 복사
df2 = df.copy()
df2.head()

id  gender  age  region
1   2       1   72       6
2   3       1   22       9
3   4       1   25       2
4   5       1  100       3
5   6       1   11       1

In [ ]:
np.random.seed(0)
a = np.random.randint(1, 5, size=(10,5))
print(a, type(a))

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>


In [ ]:
# 2차원 리스트를 데이터프레임으로 변환
list1 = a.tolist()

df3 = pd.DataFrame(list1, columns =['c1', 'c2', 'c3', 'c4', 'c5'])
print(df3.head())

   c1  c2  c3  c4  c5
0   1   4   2   1   4
1   4   4   4   2   4
2   2   3   1   4   3
3   1   1   1   3   2
4   3   4   4   3   1


In [ ]:
# 데이터프레임을 배열, 리스트, 딕셔너리로 변환
ar = df3.values
print(ar, type(ar))
print()

li = ar.tolist()
print(li, type(li))
print()

dict = df3.to_dict('list')
print(dict, type(dict))


[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] <class 'numpy.ndarray'>

[[1, 4, 2, 1, 4], [4, 4, 4, 2, 4], [2, 3, 1, 4, 3], [1, 1, 1, 3, 2], [3, 4, 4, 3, 1], [2, 2, 2, 2, 1], [2, 1, 4, 1, 4], [2, 3, 4, 4, 1], [3, 4, 1, 2, 4], [2, 4, 4, 3, 4]] <class 'list'>

{'c1': [1, 4, 2, 1, 3, 2, 2, 2, 3, 2], 'c2': [4, 4, 3, 1, 4, 2, 1, 3, 4, 4], 'c3': [2, 4, 1, 1, 4, 2, 4, 4, 1, 4], 'c4': [1, 2, 4, 3, 3, 2, 1, 4, 2, 3], 'c5': [4, 4, 3, 2, 1, 1, 4, 1, 4, 4]} <class 'dict'>


In [3]:
import numpy as np
import pandas as pd

df5 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [24, 27, 22, 32, 29],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
})

df5

Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eve   29      Phoenix

In [22]:
# 행
print(df5.iloc[0:5], '\n')
print(df5.iloc[0:5, 0:2], '\n')

# 열
print(df5.iloc[:, 0], '\n')
print(df5[['Name', 'City']], '\n')

# 조건 주기
print(df5[df5['Age'] > 25])


      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
4      Eve   29      Phoenix 

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22
3    David   32
4      Eve   29 

0      Alice
1        Bob
2    Charlie
3      David
4        Eve
Name: Name, dtype: object 

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4      Eve      Phoenix 

    Name  Age         City
1    Bob   27  Los Angeles
3  David   32      Houston
4    Eve   29      Phoenix


####file 생성

In [25]:
# file 생성
import pandas as pd
file_data = pd.DataFrame({
    'col1':[1, 2, 3, 4 , 5],
    'col2':[10, 20, 30, 40, 50],
    'col3':['A', 'B', 'C', 'D', 'E']
})
print(file_data)

   col1  col2 col3
0     1    10    A
1     2    20    B
2     3    30    C
3     4    40    D
4     5    50    E


In [26]:
# CSV 파일로 저장
file_data.to_csv('file_data.csv', index=None)   # index = None을 안넣게 되면 인덱스 컬럼이 들어가게 됨

In [27]:
# 만들어진 파일 확인
!ls

file_data.csv  sample_data


In [30]:
# 파일 읽이
file_data = pd.read_csv('file_data.csv')
print(file_data, '\n', type(file_data))

   col1  col2 col3
0     1    10    A
1     2    20    B
2     3    30    C
3     4    40    D
4     5    50    E 
 <class 'pandas.core.frame.DataFrame'>


####데이터 병합

In [33]:
df_1 = pd.DataFrame({
    'col1':np.array([1,2,3]),
    'col2':np.array(['A','B','C'])
})
df_2 = pd.DataFrame({
    'col1':np.array([4,5,6]),
    'col2':np.array(['D','E','F'])
})
print(df_1)
print()
print(df_2)

   col1 col2
0     1    A
1     2    B
2     3    C

   col1 col2
0     4    D
1     5    E
2     6    F


In [35]:
#Q. dt_1과 dt_2를 행방향과 열방향으로 병합하여 출력하세요
#행방향
df_3 = pd.concat([df_1, df_2], axis=1)
print(df_3)
print()
#열방향
df_4 = pd.concat([df_1, df_2])
print(df_4)

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F

   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [36]:
# 두번쨰 컬럼만 찾기
df_4.iloc[:, 1]

0    A
1    B
2    C
0    D
1    E
2    F
Name: col2, dtype: object

In [37]:
# 'col2' 찾기
df_4[['col2']]

col2
0    A
1    B
2    C
0    D
1    E
2    F

In [38]:
# 1행까지 출력 (같은 메서드)
print(df_4.iloc[1])
print(df_4.iloc[1, :])

col1    2
col2    B
Name: 1, dtype: object
col1    2
col2    B
Name: 1, dtype: object


In [55]:
# 데이터프레임 생성(8행 5열)
import numpy as np
import pandas as pd

np.random.seed(3)
data = np.random.randint(50,100,size=(8,5))

df = pd.DataFrame(data, columns=list('abcde'))
df

a   b   c   d   e
0  92  74  53  58  50
1  71  69  60  93  91
2  60  71  88  82  70
3  94  79  89  64  76
4  67  76  72  52  52
5  51  76  55  90  96
6  83  79  92  74  57
7  93  83  65  98  87

In [57]:
# 열이름과 행이름 변경
# df_1 = df.copy()

columns={'a':'국어','b':'영어','c':'수학','d':'과학','e':'음악'}
index={0:'a',1:'b',2:'c',3:'d',4:'e',5:'f',6:'g',7:'h'}

df.rename(columns = columns, index = index, inplace=True)
df

국어  영어  수학  과학  음악
a  92  74  53  58  50
b  71  69  60  93  91
c  60  71  88  82  70
d  94  79  89  64  76
e  67  76  72  52  52
f  51  76  55  90  96
g  83  79  92  74  57
h  93  83  65  98  87

In [67]:
# 데이터프레임 생성
import numpy as np
import pandas as pd
np.random.seed(0)

data = np.random.randint(80,100,size=(5,5))
df = pd.DataFrame(data, columns=list('abcde'))
df

a   b   c   d   e
0  92  95  80  83  83
1  87  89  99  98  84
2  86  92  81  86  87
3  94  97  85  93  88
4  89  99  96  99  85

In [68]:
df1 = df.copy()
df1

# 인덱스 삽입
df1['index'] = list('가나다라마')
df1

a   b   c   d   e index
0  92  95  80  83  83     가
1  87  89  99  98  84     나
2  86  92  81  86  87     다
3  94  97  85  93  88     라
4  89  99  96  99  85     마

In [69]:
# 인덱스 세트
df2 = df1.set_index('index')
df2

a   b   c   d   e
index                    
가      92  95  80  83  83
나      87  89  99  98  84
다      86  92  81  86  87
라      94  97  85  93  88
마      89  99  96  99  85

In [72]:
# 삭제하고 싶은 커럼 (축방향 설정)
df2_1 = df2.drop('e', axis=1)
df2_1


a   b   c   d
index                
가      92  95  80  83
나      87  89  99  98
다      86  92  81  86
라      94  97  85  93
마      89  99  96  99

In [73]:
# 다시 인덱스를 번호로 세팅할때 전의 인덱스는 컬럼쪽으로 들어감
df2_2 = df2_1.reset_index()
df2_2

index   a   b   c   d
0     가  92  95  80  83
1     나  87  89  99  98
2     다  86  92  81  86
3     라  94  97  85  93
4     마  89  99  96  99

In [74]:
# 전 데이터 df2_1에서 붕떠있는 index를 삭제할때
df2_1.index.name = None
df2_1

a   b   c   d
가  92  95  80  83
나  87  89  99  98
다  86  92  81  86
라  94  97  85  93
마  89  99  96  99

In [75]:
# 딕셔서리를 정의
dict_data = {'a':[1,2,3,4,5], 'b':[4,5,6,7,8], 'c':[7,8,9,10,11], 'd':[10,11,12,13,14], 'e':[13,14,15,16,17]}

# 딕셔서리를 데이터프레임으로 변환. 인덱스를 [r0, r1, r2]로 지정
df = pd.DataFrame(dict_data, index=['r0','r1','r2','r3','r4'])
df

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

Q. df에 r5, r6 2개의 행을 추가하고 값은 0을 적용하여 출력하세요

In [79]:
import pandas as pd
import numpy as np

df_r = df.copy()

# 2가지 방법
df_r.loc['r5'] = 0
df_r.loc['r6'] = 0
df_r

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17
r5  0  0   0   0   0
r6  0  0   0   0   0

In [80]:
# new index로 만드는 방법
new_index = ['r0','r1','r2','r3','r4','r5','r6', 'r7', 'r8']
df5 = df.reindex(new_index, fill_value=0)
df5

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17
r5  0  0   0   0   0
r6  0  0   0   0   0
r7  0  0   0   0   0
r8  0  0   0   0   0

In [82]:
# 위에 거에서 원하는 행과 열만 택할때
# 방법 1
new_index = ['r0','r1','r2','r3','r4']
df1 = df5.reindex(new_index)
df1

# 방법 2 (drop)
df1 = df5.drop(df5.index[5:9])

# 방법 3 (drop)
df1 = df5.drop(['r5', 'r6', 'r7', 'r8'], axis=0)
df1

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

In [83]:
# 인덱스 기준 정렬 (ascending=False : 내림차순)
df1_s = df1.sort_index(ascending=False)
df1_s

a  b   c   d   e
r4  5  8  11  14  17
r3  4  7  10  13  16
r2  3  6   9  12  15
r1  2  5   8  11  14
r0  1  4   7  10  13

In [85]:
# 밸류 기준 정렬
df1_v = df1.sort_values(by='c', ascending=False)
df1_v

a  b   c   d   e
r4  5  8  11  14  17
r3  4  7  10  13  16
r2  3  6   9  12  15
r1  2  5   8  11  14
r0  1  4   7  10  13

####전치(행과 열 기준이 맞바뀜)
- 행과 열의 길이가 같아야 함(정방행렬)

In [87]:
# 전치
df1_1 = df1.transpose()
df1_1

r0  r1  r2  r3  r4
a   1   2   3   4   5
b   4   5   6   7   8
c   7   8   9  10  11
d  10  11  12  13  14
e  13  14  15  16  17

In [88]:
# 롤백
df1_2 = df1_1.transpose()
df1_2

a  b   c   d   e
r0  1  4   7  10  13
r1  2  5   8  11  14
r2  3  6   9  12  15
r3  4  7  10  13  16
r4  5  8  11  14  17

####연습문제

In [134]:
# Q. df1으로 데이터프레임을 생성한 후 set_index를 사용하여 ID를 인덱스 설정한 데이터프레임을 출력하세요.
df1 = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
})

df1.set_index('ID', inplace=True)
print(df1)
df1

        Name  Age
ID               
101    Alice   24
102      Bob   27
103  Charlie   22
104    David   32


Name  Age
ID               
101    Alice   24
102      Bob   27
103  Charlie   22
104    David   32

In [138]:
# Q. df2에 대해서 다음을 수행하세요.
# - set_index를 사용하여 인덱스를 설정.
# - reset_index를 사용하여 인덱스를 리셋.
df2 = pd.DataFrame({
    'ID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
})
print(df2, '\n')
df2.set_index('Name', inplace=True)
print(df2, '\n')
df2.reset_index(inplace=True)
df2

    ID     Name  Age
0  101    Alice   24
1  102      Bob   27
2  103  Charlie   22
3  104    David   32 

          ID  Age
Name             
Alice    101   24
Bob      102   27
Charlie  103   22
David    104   32 



Name   ID  Age
0    Alice  101   24
1      Bob  102   27
2  Charlie  103   22
3    David  104   32

In [139]:
# Q. df3에 대해서 reindex를 사용하여 인덱스를 변경하여 출력하세요.
df3 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [24, 27, 22, 32]
}, index=[101, 102, 103, 104])

print(df3)
df3 = df3.reindex(['Alice', 'Bob', 'Charlie', 'David'], fill_value=0)
df3

        Name  Age
101    Alice   24
102      Bob   27
103  Charlie   22
104    David   32


Name  Age
Alice      0    0
Bob        0    0
Charlie    0    0
David      0    0

In [102]:
# Q. df4에 대해서 reindex를 사용하여 인덱스를 변경하고 결측치를 0으로 채운 데이터프레임을 출력하세요.
df4 = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 27, 22]
}, index=[0, 1, 2])

print("기존 인덱스:\n", df4)

df4 = df4.reindex(['Alice', 'Bob', 'Charlie'], fill_value=0)
df4

기존 인덱스:
       Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22


Name  Age
Alice      0    0
Bob        0    0
Charlie    0    0

In [128]:
# Q. df5에서 reindex를 사용하여 특정 날짜 범위로 인덱스를 재설정하여 출력하세요.
dates = pd.date_range('2024-01-01', periods=4, freq='D')
df5 = pd.DataFrame({
    'Value': [10, 20, 30, 40]
}, index=dates)

print(df5)
# df5 = df5.reindex(dates)
# df5

# 특정 날짜 범위 생성
new_dates = pd.date_range('2024-01-05', '2024-01-08')

# DataFrame의 인덱스를 재설정
df5_reindexed = df5.reindex(new_dates)

# 결과 출력
print(df5_reindexed)
df5.info()

            Value
2024-01-01     10
2024-01-02     20
2024-01-03     30
2024-01-04     40
            Value
2024-01-05    NaN
2024-01-06    NaN
2024-01-07    NaN
2024-01-08    NaN
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4 entries, 2024-01-01 to 2024-01-04
Freq: D
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Value   4 non-null      int64
dtypes: int64(1)
memory usage: 236.0 bytes


In [123]:
# Q. 데이터프레임 df6를 전치하고, 전치된 데이터프레임을 정리하여 연도별 판매량 데이터를 제품별로 나열하여 출력하세요.
data = {
    'Year': ['2020', '2021', '2022'],
    'Product_A': [500, 600, 700],
    'Product_B': [400, 500, 600],
    'Product_C': [300, 400, 500]
}
df6 = pd.DataFrame(data)
print(df6)

a = [0, 1, 2]
df6 = df6.transpose()
df6.rename(columns=df6.iloc[0], inplace=True)	# 행열이 전환된 데이터프레임의 열 이름 제대로 수정
# df6
df6.drop(df6.index[0], inplace=True)
# # d6f = df6.drop(df6.index[0])
df6

   Year  Product_A  Product_B  Product_C
0  2020        500        400        300
1  2021        600        500        400
2  2022        700        600        500


2020 2021 2022
Product_A  500  600  700
Product_B  400  500  600
Product_C  300  400  500

In [145]:
# 강사님 버전
data = {
    'Year': ['2020', '2021', '2022'],
    'Product_A': [500, 600, 700],
    'Product_B': [400, 500, 600],
    'Product_C': [300, 400, 500]
}
df6t = pd.DataFrame(data)
print(df6t)

# 데이터프레임 전치
df6_trans = df6t.set_index('Year').T
print(df6_trans)

# 전치되 데이터프레임 정리
# reset_index를 사용하여 인덱스를 리셋하고, rename을 사용하여 index 열을 product로 변경
df6_trans.reset_index(inplace=True)
df6_trans.rename(columns={'index': 'product'}, inplace=True)
df6_trans


   Year  Product_A  Product_B  Product_C
0  2020        500        400        300
1  2021        600        500        400
2  2022        700        600        500
Year       2020  2021  2022
Product_A   500   600   700
Product_B   400   500   600
Product_C   300   400   500


Year    product  2020  2021  2022
0     Product_A   500   600   700
1     Product_B   400   500   600
2     Product_C   300   400   500