Task1_0827. 2행 3열 텐서의 크기를 3행 2열로 변경하세요.
- view 사용
- reshape 사용
- transpose 사용

In [3]:
import torch

x = torch.rand(2, 3)
print(x)

tensor([[0.7834, 0.2397, 0.4501],
        [0.2358, 0.9900, 0.4472]])


In [4]:
# view
y = x.view(3, 2)
print(y)

tensor([[0.7834, 0.2397],
        [0.4501, 0.2358],
        [0.9900, 0.4472]])


In [5]:
# reshape
y = x.reshape(3, 2)
print(y)

tensor([[0.7834, 0.2397],
        [0.4501, 0.2358],
        [0.9900, 0.4472]])


In [6]:
# transpose
y = x.T
print(y)

z = x.transpose(0, 1)
print(z)

tensor([[0.7834, 0.2358],
        [0.2397, 0.9900],
        [0.4501, 0.4472]])
tensor([[0.7834, 0.2358],
        [0.2397, 0.9900],
        [0.4501, 0.4472]])
